### ISSUE TITLE
2 хот-кея на одну функцию

### ISSUE THREAD

**Issue by antshar** [Aegel5/SimpleSwitcher#12]
Здравствуйте. Скажите, а где хранятся текущие настройки программы (горячие клавиши, назначенные пользователем)?
Логично было бы предположить, что в файле `settings.ini` рядом с `.exe` самой программы, однако, если открыть в блокноте и изменить какие-то сочетания вручную, после запуска программы, значения остаются прежними, что свидетельствует о том, что текущие сочетания клавиш хранятся где-то в другом месте.

**Comment by Aegel5** [comment]
Добрый день, настройки хранятся в settings.ini, но, к сожалению, в hex-формате, так что их сложно поменять вручную. Планируется это доработать...

**Comment by antshar** [comment]
Изначальная причина моего вопроса заключается в том, что мне нужно добавить два разных сочетания на одно действие (переключение языка), вот я и пробовал продублировать строку и добавить еще одно сочетание, а оказалось, что даже одну строку нельзя поменять, настройки откуда-то восстанавливаются прежние. Даже если полностью удалить `settings.ini`, при повторном запуске программы, создастся новый файл с теми же настройками, что были раньше.

Может быть можно как-то иначе назначить еще одно сочетание?

**Comment by Aegel5** [comment]
Две комбинации на одно действие тоже нельзя сделать :(
Вы уже не первый, кто просит об этом, может когда-нибудь и сделаю, но сейчас разработка в заморозке...

**Comment by antshar** [comment]
Быть может, Вы бы могли подсказать, где в исходниках это находится, чтобы хотя бы просто захардкодить две комбинации и собрать отдельную версию? Уж больно нужна эта фича. Среди всех аналогов, что существуют в сети (я тщательно опробовал доброю долю, 10 так точно), Ваша программа SimpleSwitcher работает стабильнее и надежнее всех.

**Comment by Aegel5** [comment]
:) Ну если хардкодить , то можно сюда добавить: Hooker::GetTypeForKey, но тогда если программа будет обновлена, придется мержить и пересобирать.

ChotKey из строки получается этой функцией: FromString
На выходе должен быть тип HotKeyType

**Comment by antshar** [comment]
Я немного полистал код и обнаружил, что структура `CHotKeySet` имеет два поля: `def` и `def2`. Я полагаю, это две разные комбинации могут быть.

Что если тут
https://github.com/Aegel5/SimpleSwitcher/blob/e3ce918a476adbf89940be8d133f83d227f3fc9b/SimpleSwitcher/src/Settings.cpp#L113-L116

заменить на 
```cpp
CHotKeySet set;
set.def = CHotKey(VK_SHIFT, VK_CTRL);
set.def2 = CHotKey(VK_CTRL, VK_SHIFT);
AddHotKey(hk_CycleCustomLang, set);
```
Сделает ли это переключение на следующий язык как при помощи `Ctrl+Shift`, так и `Shift+Ctrl`?

**Comment by Aegel5** [comment]
Актуально еще? В принципе, можно добавить функционал, чтобы одну функцию 2-мя разными хоткеями можно было вызывать.

**Comment by antshar** [comment]
Да, очень актуально! Конечно, как Вы сказали, наиболее гибким был бы вариант с файлом настроек в JSON формате, который мог быть полностью кастомизирован и дополнен любым количеством любых шорткатов.

Я понимаю, что это может занять намного больше усилий на создание, поэтому я буду счастлив получить хоть в каком-либо виде возможность присвоить две комбинации.

**Comment by Aegel5** [comment]
Сбилдил новую версию 4.321 с новым json конфигом. Функционал новый, так что могут быть ошибки.

**Comment by antshar** [comment]
Пару дней тестирую, пока никаких ошибок не возникало. Выражаю огромную благодарность за реализацию данного функционала!

**Comment by Aegel5** [comment]
ok, тогда баг закрываю. Спасибо за благодарность) Я уже давно хотел переделать конфиг, а тут выдался повод) А еще я только сейчас понял, что у вас комбинация по сути одна и та же Ctrl+Shift, только порядок меняется. Логичнее, наверное, было добавить флажок типа "игнорировать порядок", думаю заведу на это отдельный баг.
