### ISSUE TITLE
Автоматическая конвертация раскладки

### ISSUE THREAD

**Issue by AnrDaemon** [Aegel5/SimpleSwitcher#15]
Определение языка по частотным парам практически без сбоев работает от трёх символов.
Единственное, чего нехватает в программе. Ну, кроме нормально работающего интерфейса.

**Comment by Aegel5** [comment]
В ближайшее время врядли я буду это реализовывать. Лично мне, как программисту, такая функция только мешает, но для обычного набора текста, не спорю, может быть полезна. На всякий случай скажу, что есть есть похожая программа где это уже реализованно: https://github.com/BladeMight/Mahou Можете попробовать.

**Comment by AnrDaemon** [comment]
Mahou клинит на консольных программах.
А индикатор раскладки не посоветуете? А то все куда-то пропали и поиском не ищутся.

**Comment by Aegel5** [comment]
Я про такое не слышал, чтобы были отдельные индикаторы раскладки)

**Comment by AnrDaemon** [comment]
Были, раньше много было, все пытались с пунтосвичером конкурировать.
