### ISSUE TITLE
"Several words" переключает только последнее слово

### ISSUE THREAD

**Issue by AnrDaemon** [Aegel5/SimpleSwitcher#18]
Ради интереса попробовал вместо "последнего слова" поставить переключение на "несколько слов". Работает очень странно. Если назначена Break - переключает только последнее слово. Если назначить какую-то другую кнопку - переключает, как б-г на душу положит. Может одно слово, может два.

**Comment by Aegel5** [comment]
Идея в том, что эта функция переключает сначала 1 слово, потом 2 потом 3 и так далее, т.е. ее удобно использовать совместно с основным переключением. Поэтому она и назначена на Shift+Caps.

**Comment by Aegel5** [comment]
Единственно, я бы хотел, чтобы отпускание Shift при переключении (т.е. полное отпускание клавиши), сбрасывал бы счетчик кол-ва слов для переключения - вот это ошибка, это да, исправлю в ближайшее время.

**Comment by AnrDaemon** [comment]
Просто не делать? Переключение выделенного текста покрывает 99% случаев, и намного быстрее.

**Comment by Aegel5** [comment]
Ну кому как. Мне эта функция кажется удобной. Пускай у пользователя будет выбор.

**Comment by Aegel5** [comment]
Закрываю баг, так как не понятна актуальность.
