### ISSUE TITLE
Конвертация капитализации выделенного текста

### ISSUE THREAD

**Issue by AnrDaemon** [Aegel5/SimpleSwitcher#19]
Очень… очень нужная порой фича.

**Comment by Aegel5** [comment]
Согласен, иногда бывает нужно.

**Comment by Dreamer-4pda** [comment]
А у меня она иногда сама так делает, приходится несколько раз туда-сюда конвертировать.

**Comment by Aegel5** [comment]
> А у меня она иногда сама так делает, приходится несколько раз туда-сюда конвертировать.
Не очень понятно, в чем проблема.

**Comment by Aegel5** [comment]
Функция добавлена в 5.103

**Comment by Dreamer-4pda** [comment]
> 

При изменении раскладки слова или фразы она становится капсом

**Comment by Aegel5** [comment]
> > 
> 
> При изменении раскладки слова или фразы она становится капсом

Shift видимо плохо отжимается. Это в каком-то конкретном приложении случается или везде бывает?

**Comment by Dreamer-4pda** [comment]
Рандомно, закономерности не заметил, понаблюдаю ещё

**Comment by Aegel5** [comment]
> Рандомно, закономерности не заметил, понаблюдаю ещё

Какая ОС? Я думаю, все же от приложения зависит, ну либо же что-то не так с самой ОС.

**Comment by Aegel5** [comment]
Закрываю исходный баг, создавайте ошибка будет повторяться.
