### ISSUE TITLE
Sciter

### ISSUE THREAD

**Issue by Mikanoshi** [Aegel5/SimpleSwitcher#2]
Не хочет работать исправление выделенного текста в программах на движке Sciter:
https://sciter.com/sdk/sciter-sdk.zip
(открыть \samples\forms\inputs.htm в \bin\64\sciter.exe)
Например по комбинации Shift+Pause.
Просто Pause работает для исправления последнего слова.

**Comment by alexzh2** [comment]
Функция "исправление выделенного текста" реализована через костыли (через буфер обмена) и по-хорошему ее вообще нужно выпилить, так как с ней постоянно проблемы. Лично я ей не пользуюсь, мне хватает и обычного переключения.

**Comment by Mikanoshi** [comment]
Никаких проблем не заметил, только не работает в некоторых программах =)

**Comment by alexantr** [comment]
Функцию "исправление выделенного текста" лучше оставить

**Comment by Mikanoshi** [comment]
Да как не работало, так и не работает) Пробовал последнюю версию (не понял кстати как там кнопки переназначать, из конфига старые прочитались, и то не все).

**Comment by Aegel5** [comment]
Новая версия проба пера wxWidgets)) Теперь хотя бы интерфейс можно изменять, а не гвоздями все прибито как было на winapi. 
Двойным щелчком пока назначаются хоткеи. 
Открываю баг снова.

**Comment by Aegel5** [comment]
Скачал скитер - действительно не работает. Без понятия, но почему то скиттер в упор не хочет видеть Ctrl+C когда ему присылают. 
Добавил очередной sleep и вроде как заработало, но нет гарантии, что будет работать надежно. Залил фикс в версию 4.0.1.5

**Comment by Mikanoshi** [comment]
Читается "сайтер" :) Спасибо, вроде пашет.
