### ISSUE TITLE
Ошибка прорисовки интерфейса

### ISSUE THREAD

**Issue by kirill-1000** [Aegel5/SimpleSwitcher#20]
![2022-07-12 14_26_52-Window](https://user-images.githubusercontent.com/43751913/178479570-c37f7666-27d1-4d9f-abd4-9b9f16a3ae29.png)
Начиная с  4-го релиза окно программы выглядит так. Не компилировал, скачивал релиз. ОС Win10 запущена под админскими правами. Предполагаю что не хватает какой то библиотеки?

**Comment by Aegel5** [comment]
Так выглядит wxWidget по умолчанию)
Можно с цветами подмутить чего-нить типа увеличить отступ и серый фон добавить для рамки окна. 
Пускай баг пока висит)

**Comment by Aegel5** [comment]
Оставляю интерфейс пока так, закрываю баг.
