### ISSUE TITLE
Некорректное создание задачи на автозапуск

### ISSUE THREAD

**Issue by AnrDaemon** [Aegel5/SimpleSwitcher#21]
Реальный путь к программе: 
`D:\Profiles\anrdaemon\AppData\Roaming\Programs\SimpleSwitcher\SimpleSwitcher.exe`
Путь в задаче:
`d:\profiles\anrdaemon\appdata\roaming\programs\simpleswitcher\simpleswitcher.exe`

Никогда так не делайте!

**Comment by Aegel5** [comment]
А в чем ошибка? Регистр букв теряется? 
В принципе, можно регистр и не трогать, но в windows регистр не имеет значение.

**Comment by AnrDaemon** [comment]
> в windows регистр имени файлов не имеет значения.

Это в общем случае неверно. Ибо кроме собственных FS Windows умеет работать и с другими, где регистр имеет значение. Так же можно настроить регистрозависимость для локальных томов NTFS.

**Comment by Aegel5** [comment]
ok, тогда исправлю.

**Comment by Aegel5** [comment]
Исправлено в версии 4.173

**Comment by Aegel5** [comment]
В общем закрываю баг, если что не так, можно переоткрыть.
