### ISSUE TITLE
Не та раскладка после переключения

### ISSUE THREAD

**Issue by Dreamer-4pda** [Aegel5/SimpleSwitcher#22]
У меня подключена клавиатура от apple
Она имеет немного другую раскладку, но я создал свой файл раскладки и использую его.
После смены раскладки с английского на русский при помощи Simple switcher включается стандартная русская раскладка.
В таскбаре при этом новой раскладки не появляется. Для выбора моей раскладки приходится переключить на английский, а потом снова на русский средствами системы.

Может сделать в приложении выбор раскладок между которыми переключаться?

**Comment by Aegel5** [comment]
> Может сделать в приложении выбор раскладок между которыми переключаться?

Такая функция уже есть. Называется "work only with this layouts"

**Comment by AnrDaemon** [comment]
Известный прикол винды. Просто удалите лишнюю раскладку. Она периодически будет вылезать, с этим мало что можно сделать, но удалив её однажды, до перезагрузки обычно можно жить спокойно.

**Comment by Aegel5** [comment]
Закрываю.
