### ISSUE TITLE
Выдавать сообщение при попытке использовать capslock вместо f24

### ISSUE THREAD

**Issue by gamau** [Aegel5/SimpleSwitcher#26]
Пишу слово "привет" на английской раскладке:
![изображение](https://user-images.githubusercontent.com/24148141/184814455-f5d99556-5b68-4726-a8a3-bd01bb01cd8b.png)

Нажимаю Caps Lock для исправления раскладки последнего слова. Получаю "ПРИВЕТ" в верхнем регистре:
![изображение](https://user-images.githubusercontent.com/24148141/184814609-1e989dad-1fd9-4b3a-a6c5-2687e146d968.png)

Ожидаю "привет" в нижнем регистре. Возможно требуется изменить настройки, но не нашел какие. 

**Версия SimpleSwitcher**: Build on 'Jul 31 2022'
**Выпуск ОС:** Windows 11 Pro, 
**Версия ОС:** 21H2

**Конфигурационный файл** (пересохранил в txt): [conf.txt](https://github.com/Aegel5/SimpleSwitcher/files/9348459/conf.txt)

**Comment by Aegel5** [comment]
Добрый день. Судя по вашему конфигу, вы назначили исправление на CapsLock.

```
        "hk_RevertLastWord": [
            "CapsLock"
        ],
        "hk_RevertSelelected": [
            "Shift + CapsLock"
        ],
```
И, видимо, просто включается режим Caps

Назначение на CapsLock нужно делать через клавишу F24, подробнее: https://github.com/Aegel5/SimpleSwitcher/discussions/14

**Comment by Aegel5** [comment]
Что исправлять: добавить messagebox если пользователь пытается использовать клавишу CapsLock вместо F24.

**Comment by gamau** [comment]
Добрый день! 
Инструкция: 
`Назначение на CapsLock нужно делать через клавишу F24, подробнее: https://github.com/Aegel5/SimpleSwitcher/discussions/14`
помогла! 
Большое спасибо, удаляю Punto Switcher :)

**Comment by Aegel5** [comment]
Рад был помочь)
