### ISSUE TITLE
Использовать только эти раскладки баг

### ISSUE THREAD

**Issue by subw0fer** [Aegel5/SimpleSwitcher#32]
Есть три раскладки En, Ru, De, назначил в "Использовать только эти раскладки", только En и Ru, так как немецкий использую мало.

Пользуюсь клавишей циклической смены раскладки, например Ctrl.

Так вот непонятно от чего, иногда проскакивает De при переключении.

**Comment by Aegel5** [comment]
Какая версия Windows?

**Comment by subw0fer** [comment]
Win 10 x64

**Comment by Aegel5** [comment]
Попробовал повторить у себя - работает стабильно, не понятно в чем может быть дело. Если ошибка все еще актуальна, попробуйте повторить ее на последней версии, с включенной опцией "debug log" и отправьте логи сюда.
