### ISSUE TITLE
Не переключает раскладки в KeePass

### ISSUE THREAD

**Issue by mrc16** [Aegel5/SimpleSwitcher#33]
Настроил переключение Ru <-> En на левый и правый Shift c учетом keyup.
Но в KeePass не работает, также в нем не работает конвертация по Break.

Keepass 2.53, Windows 10 x64.

**Comment by Aegel5** [comment]
Добрый день. Да, была когда-то проблема в keepass, но она исправлялась (c помощью хаков). Может снова появилась, посмотрю. 
На всякий случай скажу, что в KeepassXC работает нормально.

**Comment by Aegel5** [comment]
Проверьте на последней версии. В keepass 2.x должно все нормально работать.

**Comment by mrc16** [comment]
Всё работает, огромное спасибо!
