### ISSUE TITLE
Добавить опцию "Сворачивать вместо закрытия по нажатию крестика в окне"

### ISSUE THREAD

**Issue by killermill** [Aegel5/SimpleSwitcher#36]
Когда заходишь в окно настроек, например ненадолго переключить режим работы, в конце интуитивно жмешь ✖  (закрыть окно), вместо кнопки "Свернуть в трей". Может быть можно добавить галочку в "Настройки" чтобы менять поведение программы по нажатию ✖.

**Comment by Aegel5** [comment]
Не совсем понял. Сейчас поведение такое. 

`Закрыть` -> Закрывает
`Свернуть в трей` -> сворачивает. 
 ✖-> сворачивает.

Если у вас не так работает, значит это баг.

**Comment by killermill** [comment]
Сегодня обновил версию и действительно так работает как надо. Возможно я в голове у себя перепутал.
Прошу прощения за потраченное на меня время. Спасибо за отличный софт.

**Comment by Aegel5** [comment]
Ничего страшного)))
