### ISSUE TITLE
Application does not start

### ISSUE THREAD

**Issue by DavisR-GitHub** [Aegel5/SimpleSwitcher#37]
Hi,
Application works fine on one my system and does not want to even start on another - virtual machine.
It shows Message Box: "Unhandled unknown exception; terminating the application" and exits.

It works on host machine and does not want to work on VMWare Workstation guest on that host.
Environment is almost same: Win 10 x64 Pro.

How to debug it?

**Comment by Aegel5** [comment]
Hello. The debug log may help (it can be enabled in json file before program start or copied from worked machine, parametr "fDbgMode": true)
But the best solution if you are run debug verison of SS and make full dump on crash. I can build debug build it.

**Comment by Aegel5** [comment]
![Безымянный](https://user-images.githubusercontent.com/10333681/218847696-168fbd30-290d-4f92-8ddc-9fbb2c6c34aa.png)

**Comment by DavisR-GitHub** [comment]
> I can build the debug version

Come on

**Comment by DavisR-GitHub** [comment]
Log:
`15.02|11:29:14.653|10572 Log level now 3
15.02|11:29:14.653|10572 HResult=-2147417850(0x80010106) utils/COM_utils.h(37) 
15.02|11:29:14.653|10572 TStatus=SW_ERR_HRESULT(12) decent_app.cpp(41) 
15.02|11:29:14.775|08572 StartMonitor...
15.02|11:29:14.775|08572 StartCycle...
15.02|11:29:14.775|07008 ClearsKeys
15.02|11:29:14.775|08572 HookGlobal...
15.02|11:29:14.775|07008 Exit main worker`

**Comment by Aegel5** [comment]
I tried it on my vmware - everything works fine. I think there are some problems in the guest OS itself - the process failed on the initialization of wxwidget lib. I updated wxWidget to last version - you can try this. Also maybe a more detailed error message will appeared now.

**Comment by DavisR-GitHub** [comment]
Yep, strange error. I know when it can appear.
0x80010106 is RPC_E_CHANGED_MODE.
CoInitializeEx can return this if thread had already successfully call CoInitializeEx with different concurrency model.
This can be as a result of bad app design but it should be repeatable not floating error.

**Comment by Aegel5** [comment]
No, this error has nothing to do with crash.

**Comment by DavisR-GitHub** [comment]
![изображение](https://user-images.githubusercontent.com/44195644/219041086-71f43784-e83d-4481-b6fa-f4f19efb8464.png)

```
15.02|15:31:18.486|03452 Log level now 3
15.02|15:31:18.486|03452 HResult=-2147417850(0x80010106) utils/COM_utils.h(37) 
15.02|15:31:18.486|03452 TStatus=SW_ERR_HRESULT(12) decent_app.cpp(41) 
15.02|15:31:18.564|06904 StartMonitor...
15.02|15:31:18.564|06904 StartCycle...
15.02|15:31:18.564|06956 ClearsKeys
15.02|15:31:18.564|06904 HookGlobal...
15.02|15:31:18.564|06956 Exit main worker
```

**Comment by Aegel5** [comment]
5.160 - added some fixes.

**Comment by DavisR-GitHub** [comment]
It works now!
Great

**Comment by DavisR-GitHub** [comment]
Oops, it starts but dies not works.
After I set keys for langs it does not switch them, and forget these setting after restart
[SimpleSwitcher.exe(6536)_262328.log](https://github.com/Aegel5/SimpleSwitcher/files/10744016/SimpleSwitcher.exe.6536._262328.log)

**Comment by Aegel5** [comment]
Sorry it was with new errors... I build a new one)

**Comment by DavisR-GitHub** [comment]
It's OK )
Seems like now it works fine
[SimpleSwitcher.exe(9068)_859500.log](https://github.com/Aegel5/SimpleSwitcher/files/10744125/SimpleSwitcher.exe.9068._859500.log)

**Comment by Aegel5** [comment]
Good) Although there are still oddities with encoding in the log. Will fix this later..  It seems the problem was because of the unknown name of some key (maybe scancode remaped)
