### ISSUE TITLE
Лишний третий язык при циклической смене

### ISSUE THREAD

**Issue by birza4you** [Aegel5/SimpleSwitcher#4]
Постоянно борюсь с третьим лишним языком (Английский Соединённое королевство), при использовании программы на Windows 10 x64
Настроил смену раскладки на LShift+RShift (самый удобный на мой взгляд способ).
Однако программа при переключении с русского на английский срабатывает с одного нажатия этих двух клавиш, а вот обратно приходится делать это дважды, т.к. она сначала переключает с Английского США на Английский Королевства. Хотя его просто нет в системе. Пробовал бороться в самой винде, ставил его и тут же удалял, но это не помогает.
Может просто выпилить третий язык вообще из вашего переключателя? В остальном он замечательный.
Странно, что на Win7 Pro таких проблем не наблюдаю (на рабочем компе).
Видимо как-то в 10-ке по другому драйвера работают.
Помогите это как-то исправить пожалуйста.
Сергей.
p.s. Установка и затем удаление третьего языка из системы помогает исправить эту проблему, но только до следующей перезагрузки. Причём, в тот момент когда проблема наблюдается третьего языка нет в системе. Облазил все форумы, но решение видимо не в винде,  а в вашей программе. Т.к. с другими программами для смены раскладки я такого не наблюдаю (однако крайне мало кто поддерживает смену языка по LShift+RShift

**Comment by birza4you** [comment]
Это прямо единственная проблема, которая мешает использовать вашу программу (((

**Comment by lSeverl** [comment]
+1, не хватает переключения между двумя выбранными языками.

**Comment by alexzh2** [comment]
> Постоянно борюсь с третьим лишним языком (Английский Соединённое королевство), при использовании программы на Windows 10 x64
Третий язык в Windows 10 - известный баг. У меня тоже такое было и я удалял через powershell (что-то вроде этого: https://www.outsidethebox.ms/19024/)

**Comment by alexzh2** [comment]
> +1, не хватает переключения между двумя выбранными языками.

Есть функция циклической смены между любым набором языков.

**Comment by hsb5** [comment]
> Есть функция циклической смены между любым набором языков.

Т.е. функция есть, но получается, что она в виндовс 10 не работает, верно я понимаю?

**Comment by alexzh2** [comment]
> > Есть функция циклической смены между любым набором языков.
> 
> Т.е. функция есть, но получается, что она в виндовс 10 не работает, верно я понимаю?

Если нет проблем с третьим языком, то все должно работать.

**Comment by lSeverl** [comment]
Дело не в третьем языке, а в функции переключения между двумя (избранными) языками.
Например у меня три языка: **ENG, RU, UA**. 
Удобно настроить переключение только между **ENG и RU** и обратно. Минус N действий если в ОС более двух установленных языков.

**Comment by alexzh2** [comment]
> Удобно настроить переключение только между **ENG и RU** и обратно. Минус N действий если в ОС более двух установленных языков.
Такая функция ЕСТЬ в программе: сменить раскладку (циклически между выбранными языками)

**Comment by alexzh2** [comment]
> Дело не в третьем языке, а в функции переключения между двумя (избранными) языками.
> Например у меня три языка: **ENG, RU, UA**.
> Удобно настроить переключение только между **ENG и RU** и обратно. Минус N действий если в ОС более двух установленных языков.

Такая функция в программе есть: сменить раскладку (циклически между выбранными языками). Но, к сожалению, она не работала (
Я исправил ее в версии 2.1.0.1.

**Comment by lSeverl** [comment]
@alexzh2 
Спасибо, теперь работает смена расскладки :).
Но не работает так, как ожидалось.
Допустим я наинаю набирать и уже набрал часть фразы, обнаружил, что не та раскладка. Нужно сменить ее и последнее слово или фразу тоже. Сейчас приходится три раза нажимать, чтобы появилось нужное. Было бы неплохо связать переключение между двумя языками и функционал "Исправить раскладку". А в целом программа супер, замена громоздкому пунтасвитчеру :). 
С наилучшими пожиланиями, Алексей

**Comment by alexzh2** [comment]
Я добавил две команды CustomLang_RevertLastWorld и CustomLang_RevertCycle в config.lua. Попробуйте, может решит вашу проблему. Версия 2.1.2.0

**Comment by lSeverl** [comment]
> Я добавил две команды CustomLang_RevertLastWorld и CustomLang_RevertCycle в config.lua. Попробуйте, может решит вашу проблему. Версия 2.1.2.0

Да, спасибо. Теперь все СУПЕР! :)

**Comment by hsb5** [comment]
> Такая функция в программе есть: "сменить раскладку (циклически между выбранными языками)". Но, к сожалению, она не работала (
> Я исправил ее в версии 2.1.0.1.

Может я чего-то не понимаю, но у меня данная функция отказывается работать:
Воспроизведение
Windows 10 x64 (все обновления установлены)
1. Установить следующие настройки
- Сменить раскладку (циклически): shift+shift
- Сменить раскладку (циклически между выбранными языками): shift+shift
- Выбранные языки: ru-RU, en-US
2. Открыть блокнот и начать вводить текст на русском. Нажать shift+shift - ввод текста успешно переключится на английскую раскладку. Нажать shift+shift - ввод текста остаётся на английской раскладке. Повторно нажать shift+shift - вот только со второго раза раскладка меняется на русскую.
3. Т.е. чтобы вернуться на ввод в русской раскладке надо shift+shift выполнять два раза. Это явно неправильно. 
4. Третьего языка в системе не установлено.

**Comment by alexzh2** [comment]
hsb5, судя по вашему описанию, вы назначили одну и туже комбинацию клавиш сразу на две функции программы.  
Видимо, "Сменить раскладку (циклически): shift+shift" лишнее в вашем случае (должно быть пусто).

**Comment by alexzh2** [comment]
hsb5, судя по вашему описанию, вы назначили одну и туже комбинацию клавиш сразу на две функции программы.
Если у вас только два языка, то вам достаточно только: "Сменить раскладку (циклически): shift+shift"

**Comment by hsb5** [comment]
> hsb5, судя по вашему описанию, вы назначили одну и туже комбинацию клавиш сразу на две функции программы.
> Если у вас только два языка, то вам достаточно только: "Сменить раскладку (циклически): shift+shift"
> 
> Но даже если назначить как вы и описали, проблема не повторяется у меня...
> 
> Включите логирование (вкладка настройки), повторите проблему и отправьте сюда логи

1. Вот именно если включить только первую (верхнюю настройку): "Сменить раскладку (циклически): shift+shift" - то тогда проблема на 10-ке стабильно воспроизводится.
hk_ChangeLayoutCycle=0xA0A10200 -- Shift + Shift
2. Проблемы нет только если первую (верхнюю) функцию отключить, и включить только циклически для выбранных языков и задать в программе два языка принудительно. Вот тогда переключает корректно.
hk_CycleCustomLang=0xA0A10200 -- Shift + Shift
3. Логи в следующем сообщении (настройки: включен только первый параметр - менять раскладку циклически 
hk_ChangeLayoutCycle=0xA0A10200 -- Shift + Shift

**Comment by hsb5** [comment]
Логи:
[simpleswitcher.exe(4764)_5899015.log](https://github.com/alexzh2/SimpleSwitcher/files/6808108/simpleswitcher.exe.4764._5899015.log)
[SimpleSwitcher.exe(6136)_5898890.log](https://github.com/alexzh2/SimpleSwitcher/files/6808109/SimpleSwitcher.exe.6136._5898890.log)

**Comment by alexzh2** [comment]
@hsb, судя по логам у вас установлено 3 языка в системе:

```
13.07|13:21:37.803|07224 hwnd=0x00110836, pid=4308, threadid=13304, lay=0x4090409, prg=notepad.exe
13.07|13:21:39.887|07224 hwnd=0x00110836, pid=4308, threadid=13304, lay=0x8090809, prg=notepad.exe
13.07|13:21:43.181|07224 hwnd=0x00110836, pid=4308, threadid=13304, lay=0x4190419, prg=notepad.exe
```

**Comment by hsb5** [comment]
> @hsb5, судя по логам у вас установлено 3 языка в системе:
> 
> ```
> 13.07|13:21:37.803|07224 hwnd=0x00110836, pid=4308, threadid=13304, lay=0x4090409, prg=notepad.exe
> 13.07|13:21:39.887|07224 hwnd=0x00110836, pid=4308, threadid=13304, lay=0x8090809, prg=notepad.exe
> 13.07|13:21:43.181|07224 hwnd=0x00110836, pid=4308, threadid=13304, lay=0x4190419, prg=notepad.exe
> ```

У меня два языка в системе. По крайней мере работают и отображаются только два.
Возможно это какая-то особенность или ошибка в 10-ой винде держать ещё третий "скрытый" язык в системе, но его не использовать. Тогда видимо либо учитывать эту особенность 10-ой операционки, либо смириться и настраивать так как это сделал я.

**Comment by alexzh2** [comment]
Третий язык не всегда отображается, но его можно удалить, правда я не помню как это делается)

Может эта статься поможет? : https://www.outsidethebox.ms/19024/

**Comment by hsb5** [comment]
Изучил тему подробно. Блин, похоже это правда из-за удалённого подключения по рдп
Было бы здорово, если бы возможно было добавить галочку "игнорировать удалённые раскладки" в вашу программу. Это многим бы помогло, т.к. не все понимают, что проблема из-за этого. а удалённо сейчас много людей стало работать.
IgnoreRemoteKeyboardLayout

Твик реестра из статьи: https://www.outsidethebox.ms/19024/
Windows Registry Editor Version 5.00
 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
"IgnoreRemoteKeyboardLayout"=dword:00000001

**Comment by alexzh2** [comment]
@hsb5, отлично! Спасибо за информацию. Добавлю такую настройку.

**Comment by AnrDaemon** [comment]
Это на самом деле проблема не свитчера, а винды. Заявленная как "фича" ещё во времена XP - недостающие раскладки клавиатуры активируются автоматически.
Свитчер честно переключает на следующую раскладку. Вот только раскладок у вас активно больше, чем вы думаете.
Зайдите в настройки языка, откройте проблемный язык, добавьте(!) раскладку, которая вызывает проблемы и удалите её.
Проверьте, должно перестать тупить. У меня такое происходит с русским из-за того, что я не пользуюсь стандартной раскладкой. Но некоторые программы заставляют систему добавлять стандартную RU в набор.

**Comment by AnrDaemon** [comment]
> "IgnoreRemoteKeyboardLayout"=dword:00000001

Не помогает.

**Comment by Aegel5** [comment]
> > "IgnoreRemoteKeyboardLayout"=dword:00000001
> 
> Не помогает. Вернее, помогает ТОЛЬКО если проблема вызвана MSTSC. Остальным программам на эту настройку плевать.

Чтобы все идельно работало, когда больше двух языков, нужно использовать механизм "work only with this layout". Но сейчас он в консольных приложениях не работает, а чтобы заработало, нужен https://github.com/Aegel5/SimpleSwitcher/issues/9 
Первые тесты показали, что там все на хаках нужно делать, такого механизма в венде встроенного нет. В общем отложил реализацию.

**Comment by AnrDaemon** [comment]
Я сделал подборку настроек, который сильно уменьшают шансы на выпадение такого косяка.
Нужно это всё описать нормальным языком и куда-то выложить.
Консольные приложения можно пока оставить. Они потихоньку… не то, чтобы отмирают, но повсеместное распространение Windows Terminal'а сделало ситуацию намного менее острой.

**Comment by Aegel5** [comment]
На win 10 теперь должна нормально работать функция "Work only with this layouts", поэтому баг закрываю.
