### ISSUE TITLE
Remote layout switching with custom hotkey does not work

### ISSUE THREAD

**Issue by AnrDaemon** [Aegel5/SimpleSwitcher#40]
I'm using Synergy(Core) and RMS in my daily work, and in both cases remote system has SimpleSwitcher installed and configured to change keyboard layout on F24#up.

The key itself is passed correctly to the remote (i.e. the TTY terminals respond with appropriate escape sequence), but language switch is not executed.

Wonder if it is something that can be fixed.

**Comment by Aegel5** [comment]
Hello. You can try to reproduce this error with `debug log` enabled. Maybe in this scenario keys is considered as injected (and that is why it skipped).

**Comment by AnrDaemon** [comment]
> Maybe in this scenario keys is considered as injected (and that is why it skipped).

Most likely. Will try debug log.

**Comment by AnrDaemon** [comment]
Debug log reporting "skip enjected" (which looks correlated to the desired key presses) without much of the detail.

**Comment by Aegel5** [comment]
An injected mechanism used to distinguish user input from program self input. In your case, I think all typed keys have an injected flag. We need to think about how to fix this.

**Comment by Aegel5** [comment]
I'm thinking of adding the "allow remote keys" setting, and if it's enabled, not to skip injected keys, but to distinguish from self input by other heuristics.

**Comment by AnrDaemon** [comment]
Can you please explain the issue with injected keys in simple terms?
What is wrong with them and why you had to filter them in the first place?

**Comment by AnrDaemon** [comment]
Oh, I think I understand it. In order to perform requested operations, you have to inject keys yourself.
What if you simply suppress the hook until operation is completed?

**Comment by Aegel5** [comment]
First, it is possible that SS is installed on both machines and we are want for correct work also in this scenario. Therefore, the injection flag can be used not only for detect self-input, I beleive.

"Operation completed" is no such term in this api, but I think we can, for example, just count the injected keys or something like that.

**Comment by AnrDaemon** [comment]
It is installed on both host and client. Doesn't work, sadly. :cry:

**Comment by Aegel5** [comment]
Are you using RDP to connect?

**Comment by AnrDaemon** [comment]
No. [RMS](https://www.remoteutilities.com/) and [Synergy](/symless/synergy-core)

**Comment by Aegel5** [comment]
I added an experimental setting "Allow remote keys" in v5.170. In your scenario it should be enabled on the host SS. It is also advisable to add the client program (through which you connect) to exceptions on the client SS (for now, this is only possible via config file)

**Comment by AnrDaemon** [comment]
Will test, thank you.

**Comment by AnrDaemon** [comment]
After a number of attempts, this seems to work quite well. Thank you!

**Comment by AnrDaemon** [comment]
RMS is still a question, but I'll see what can I do about it. Their authors are quire responsive, too. Just not as swift :)
