### ISSUE TITLE
Неправильная работа циклической смены раскладки на RAlt

### ISSUE THREAD

**Issue by N08I40K** [Aegel5/SimpleSwitcher#41]
Использую правый альт для смены раскладки, поле нажатия раскладка меняется только с английского на русский (вне зависимости от настройки "Различать левые и правые модификаторы"), обратно не меняется. Причём на остальные кнопки (например LAlt/LCtrl/RCtrl) циклическая смена раскладки работает исправно.

**Comment by N08I40K** [comment]
Система Windows 10 x64

**Comment by AnrDaemon** [comment]
Проще использовать Caps Lock с ремапом, ей-Богу.

**Comment by Aegel5** [comment]
> Проще использовать Caps Lock с ремапом, ей-Богу.

Возможно, тут речь про смену раскладки без исправления текста. Ну и не всем caps удобен бывает.

**Comment by Aegel5** [comment]
v5.243 - теперь можно использовать RAlt
