### ISSUE TITLE
Переключение раскладки по F12 не предотвращает срабатывания F12 в текущей программе

### ISSUE THREAD

**Issue by unv-unv** [Aegel5/SimpleSwitcher#42]
Перешёл на Simple Switcher с Punto Switcher. Поскольку у меня на ноутбуке Lenovo нет клавиши Pause/Break, то я использовал в качестве клавиши переключения F12. И в Punto Switcher это работало нормально. Однако в Simple Switcher начались проблемы.

Punto Switcher перехватывал F12 полностью, не отдавая его текущей программе. А Simple Switcher позволяет текущей программе также обработать F12. Так, если я нажимаю F12 в браузере, то после переключения раскладки браузер дополнительно открывает JS-отладчик. IntelliJ Idea тоже имеет обработчик F12 — который также срабатывает после переключения раскладки. Очень неудобно.

Пытался даже включить опцию «Запретить другим программам перехватывать клавиатуру» в настройках — не помогло.

**Comment by Aegel5** [comment]
Я добавил глобальную регистрация клавиш в версию 5.169, но F12 все равно не смог зарегистрировать.

Вот что пишут в msdn: "The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key. Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident." (https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey)

**Comment by unv-unv** [comment]
Интересно, как это делает Punto Switcher.

**Comment by unv-unv** [comment]
Ну и если браузер регистрирует горячую клавишу F12 именно что для отладчика, то та же IntelliJ Idea регистрирует его не для отладчика, а для просмотра истории в Git. Да, они регистрируют горячие клавиши не глобально. Но почему нельзя перехватить горячие клавиши для текущего приложения?

В WinAPI я не разбираюсь, потому могу сказать ересь. Но по аналогии с JS API в браузере — там есть возможность перехватить событие нажатие клавиши на определённом уровне и остановить дальнейшее распространение события (Event.stopPropagation). В WinAPI нет такой возможности?

**Comment by Aegel5** [comment]
Я нашел еще один способ это сделать и вроде получилось даже. Но пока что сложновато реализовать, может сделаю в виде беты.

**Comment by unv-unv** [comment]
Большое спасибо за помощь.

**Comment by Aegel5** [comment]
Ну пока еще ничего не сделал) В winapi есть способ полностью запретить срабатывание клавиши, но он плохо ложится на текущую архитектуру программы, плюс не ясно какие side эффекты он может дать.

**Comment by AnrDaemon** [comment]
Не стоит так делать. Сделайте ремап F12 на другую клавишу, и уже её назначайте. Но F12 вы потеряете полностью. Не ситоит так делать.

**Comment by Aegel5** [comment]
> Не стоит так делать. Сделайте ремап F12 на другую клавишу, и уже её назначайте. Но F12 вы потеряете полностью. Не ситоит так делать.

Почему не стоит так делать? Ремап F12 мне видится ОЧЕНЬ плохой идеей.

**Comment by AnrDaemon** [comment]
Потому что в лучшем случае будет срабатывать только чей-то один функционал (свичера, либо программы) F12.
В худшем - будут работать оба.

А вот ремап F12 позволяет использовать F12 через osk без конфликтов функционала.

**Comment by Aegel5** [comment]
Добавил в версию 5.222
