### ISSUE TITLE
Bug in Figma

### ISSUE THREAD

**Issue by alealeks** [Aegel5/SimpleSwitcher#47]
При редактировании текстового слоя в Фигме (Windows desktop app и online-клиент в браузере), переключение работает некорректно. Сконвертированное слово добавляется после, а прежнее остается.

https://figma.com

![bugg](https://github.com/Aegel5/SimpleSwitcher/assets/11540427/312588b3-f565-4ee0-ab64-602c6f1aed5e)

Windows 11

**Comment by Aegel5** [comment]
Попробовал online клиент. Ошибку повторить не удалось.
Какая версия программы у вас?

**Comment by Aegel5** [comment]
Я так понимаю, что это одна и та же проблема - поэтому закрываю посты.

**Comment by alealeks** [comment]
Нет, отключение Microsoft PowerToys не помогает. Это другая проблема.

**Comment by alealeks** [comment]
Проверил в Windows 10, там переключается все нормально, без дублей. Видимо, дело в Windows 11.

**Comment by Aegel5** [comment]
Пока нет возможности на Windows 11 попробовать. Как появится - попробую повторить. Еще могу посоветовать потестить с опцией "Запретить другим программам перехватывать клавиатуру", может быть дело еще в каких то похожих программах, а эта опций принудительно выгружает все остальные.

**Comment by alealeks** [comment]
> могу посоветовать потестить с опцией "Запретить другим программам перехватывать клавиатуру", может быть дело еще в каких то похожих программах, а эта опций принудительно выгружает все остальные.

К сожалению, не помогло.

**Comment by Aegel5** [comment]
Попробовал повторить на последней Windows 11 на последней десктопной figma - все работает нормально. Может напишите небольшую инструкцию как повторять, а то может я не так пробую?

**Comment by alealeks** [comment]
Выбираю в инструмент "Text" (горячая клавиша "T"), кликаю на канвасе, печатаю текст, жму клавишу переключения SimpleSwitcher и вижу такое:
![123123](https://github.com/Aegel5/SimpleSwitcher/assets/11540427/ed16f45d-1037-42c8-94fb-91fe40749913)

**Comment by alealeks** [comment]
Лог готов
[SimpleSwitcher.exe(5428)_4383328.log.zip](https://github.com/Aegel5/SimpleSwitcher/files/13938342/SimpleSwitcher.exe.5428._4383328.log.zip)

**Comment by Aegel5** [comment]
Нашел одну странность в логах, но к сожалению, не все что нужно залогировалось. Сбилдил новую версию с новым логированием. Попробуйте еще раз повторить.

**Comment by alealeks** [comment]
[SimpleSwitcher.exe(13436)_705046.log.zip](https://github.com/Aegel5/SimpleSwitcher/files/13950655/SimpleSwitcher.exe.13436._705046.log.zip)

**Comment by Aegel5** [comment]
Есть странность, что сообщения по нажатым клавишам приходят не в обычном порядке, т.е. пока одна клавиша еще не отжата, другая уже нажимается (например "р" еще не отжата, а "и" уже была нажата). Это никак не должно влиять на работу SS, но может быть симптомом других проблем в системе. Больше особо идей нет. На всякий случай напишите свою версию figma и версию windows 11 (я тестил на всем последнем).

**Comment by alealeks** [comment]
Figma 116.15.4
Windows 11 Pro 23H2 22631.3007

**Comment by alealeks** [comment]
Ради эксперимента проверил в Безопасном режиме — баг воспроизвелся.

**Comment by Aegel5** [comment]
Попробуйте версию 5.286 с настройкой "Switch lang by Alt+Shift"

**Comment by alealeks** [comment]
> Попробуйте версию 5.286 с настройкой "Switch lang by Alt+Shift"

После крупного обновления Win 11 все заработало.
