### ISSUE TITLE
Add Ukrainian flag?

### ISSUE THREAD

**Issue by MOLNIO** [Aegel5/SimpleSwitcher#48]
Hello, your program is excellent, please tell me if it is possible to add the Ukrainian flag to the tray?

**Comment by Aegel5** [comment]
We will add in the next versions

**Comment by MOLNIO** [comment]
Thank you)

**Comment by Aegel5** [comment]
Added in 5.227

**Comment by MOLNIO** [comment]
> Добавлено в версии 5.227

thank you very much updated)
