### ISSUE TITLE
Добавить поддержку Caps lock без remap

### ISSUE THREAD

**Issue by subw0fer** [Aegel5/SimpleSwitcher#49]
Если поставить переключение языков на Caps lock, то не важно key up или key down, не блокирует функции капса, капс иногда прорывается накладывается на переключение. Можно это как то пофиксить? Win10 x64 22H2

**Comment by subw0fer** [comment]
Ладно, перенёс капслок на F24. Можете и дальше молчать ;-p

**Comment by Aegel5** [comment]
Рад что все само разрешилось)

**Comment by Aegel5** [comment]
1. добавить деф хоткеи
2. обновить док.
