### ISSUE TITLE
Лишние кавычки в международной раскладке

### ISSUE THREAD

**Issue by trozodemente** [Aegel5/SimpleSwitcher#5]
Windows 10 x64

При использовании приложения с международной английской раскладкой при нажатии на клавишу с апострофом (центральный ряд букв, слева от Enter: русская "э", апостроф и кавычка в английской раскладке) вместо нормального поведения выводится сразу два апострофа, то же самое с кавычками (с Shift).

Нормальное поведение с выключенным приложением такое.
После нажатия на клавишу (без Shift) ожидается дальнейший ввод, затем:
 - Если это символ с диакритическим знаком (например, ударение: á é ó или умлаут (с Shift) ä ë ö), то выводится этот символ.
 - Если это другой символ, то выводится апостроф (или кавычка, если при наборе был зажат Shift), а затем этот символ: '2 't или "r "h.
 - Если нажат пробел, то выводится только апостроф или только кавычка, без следующего пробела.

Можно ли как-то сохранить нормальное поведение при использовании международной раскладки? Иначе получается, что приложение лишает международную раскладку смысла, большое количество спецсимволов в ней работает так, как описано выше.

**Comment by alexzh2** [comment]
Извиняюсь за долгий ответ. Не могли бы вы поконкретнее описать в чем проблема? Проблема со сменой раскладки по хоткею или программа просто в фоновом режиме мешает набору текста?

**Comment by Aegel5** [comment]
Закрываю баг, так как не понятна актуальность. Если все еще нужно - переоткройте.
