### ISSUE TITLE
Telegram input issue

### ISSUE THREAD

**Issue by alealeks** [Aegel5/SimpleSwitcher#50]
Добрый день!

Для примера, попробуйте написать в поле ввода Telegram Desktop "e nt,z" и нажать клавишу конвертации раскладки. Для получения более интересного результата нажмите несколько раз.

![telegram](https://github.com/Aegel5/SimpleSwitcher/assets/11540427/7b2897a2-2284-48f6-ac55-cc0e7e2cda73)

Windows 11

**Comment by alealeks** [comment]
Версия скачивалась из вашего гита.

**Comment by Aegel5** [comment]
На какую клавишу происходит переключение?

**Comment by alealeks** [comment]
![2023-11-29_22-16-39](https://github.com/Aegel5/SimpleSwitcher/assets/11540427/355c212c-1184-423c-bed6-843fa0161356)

**Comment by alealeks** [comment]
только что сменил переключение на другую клавишу, потом снова вернул break и вроде как стало нормально переключаться в телеграмме и в outlook(new)

**Comment by Aegel5** [comment]
Я думаю дело в Windows 11. Были уже похожие проблемы с ней.

**Comment by Aegel5** [comment]
Само собой, с другими похожими программами могут быть конфликты...

**Comment by alealeks** [comment]
Кстати, этот комбайн от Микрософта вбирает в себя модули сторонних разработчиков с Гита, вдруг вам будет интересно.

**Comment by alealeks** [comment]
Все-таки виновником оказался другой модуль.

![image](https://github.com/Aegel5/SimpleSwitcher/assets/11540427/7dea10d9-de31-4a8b-84fe-a8fdc2f218a2)
