### ISSUE TITLE
Excel selection/insertion

### ISSUE THREAD

**Issue by Timmmich19** [Aegel5/SimpleSwitcher#57]
When working in Excel, there is a problem with insert parameters, format by pattern and other similar functions that work with selection. As far as I understand it happens because SimpleSwitcher intercepts the selection and insertion thread. This is similar to the problem with clamped ScrolLock. When selecting and copying, the selection sliders disappear after a second (checked in another LibreOffice tabular processor this problem does not occur).

To see the problem, it is necessary to have ScrolLock turned off, because it can cause the same problem (but it is not the case). You should also reset InputSettings to default in Excel settings to avoid pitfalls.

Thanks!
![image](https://github.com/Aegel5/SimpleSwitcher/assets/70585632/ddc746e9-1a04-48d9-a458-c731c8e0b932)

**Comment by Aegel5** [comment]
Hello. 
What version of excel?
Please write steps to reproduce the error.

**Comment by Timmmich19** [comment]
Office Home 2016 pack for Studying
1) Simple switcher on Startup apps (to start at the system boot)
2) Create new excel list
3) Made formating for some cells
4) Try to copy formating of this cells by using appropriate tool in excel
5) Paste formating to other cells 
Thanks!

**Comment by Aegel5** [comment]
Can't reproduce.
1) Are you sure you are not using option "Clear text format on Ctrl-C"?
2) 
> Try to copy formating of this cells by using appropriate tool in excel

What this tool is?
