### ISSUE TITLE
Не запускается windows

### ISSUE THREAD

**Issue by Maxutka00** [Aegel5/SimpleSwitcher#60]
После переназначения caps lock на f24, оно просит перезапустить комп. И после этого винда не запускается ни в каком режиме. Windows 11 версия последняя (не помню точно).

**Comment by Aegel5** [comment]
Может вирусы или еще что-нибудь. Этот функционал никак не должен влиять на возможность запуска. А вообще CapsLock теперь можно использовать без переназначения. В ближайшее время поменяю дефолты.

**Comment by Maxutka00** [comment]
> Может вирусы или еще что-нибудь. Этот функционал никак не должен влиять на возможность запуска. А вообще CapsLock теперь можно использовать без переназначения. В ближайшее время поменяю дефолты.

С помощью dism и sfc всё исправил. Вероятно просто обнова винды её и убила, с прогой всё окей

**Comment by Aegel5** [comment]
Я сбилдил новую версию с измененными дефолтами для CapsLock. Теперь можно без переназначения использовать.
