### ISSUE TITLE
Регресс в смене раскладок, начиная с версии 5.241

### ISSUE THREAD

**Issue by VladWinner** [Aegel5/SimpleSwitcher#61]
Пример:
![image](https://github.com/user-attachments/assets/e85bd5c3-0c3e-41bc-8b77-aa3e96576b7f)
В версиях по v5.227 включительно допускалось срабатывание переключения раскладки при зажатой первой клавише.
В моем примере переключение назначено на Ctrl+Пробел. Если я продолжаю удерживать Ctrl, то повторная смена раскладки посредством нажатия Пробела полностью работает. В версии v5.241 и новее теперь это стало невозможно: чтобы переключить раскладку ещё раз, обязательно требуется отпустить клавишу Ctrl, что делает процесс менее интуитивным и удобным

v5.227:
Ctrl+Пробел = смена раскладки
Ctrl+Пробел+Пробел = снова смена раскладки

v.5241+:
Ctrl+Пробел = смена раскладки
Ctrl+Пробел+Пробел = ничего не происходит

**Comment by Aegel5** [comment]
Сбилдил новую версию. Надеюсь другой функционал не отвалится)

**Comment by AnrDaemon** [comment]
В https://github.com/Aegel5/SimpleSwitcher/releases/tag/5.276 отвалилось переключение выделенного текста. В 275 ещё работало.

**Comment by Aegel5** [comment]
> В https://github.com/Aegel5/SimpleSwitcher/releases/tag/5.276 отвалилось переключение выделенного текста. В 275 ещё работало.
> 
> Хоткей стоит `Shift+Break #up`.
> 
> Кстати, назначение кнопок тоже фонит.

Откатил исправления, сделал по-другому.

**Comment by AnrDaemon** [comment]
Спасибо, починилось.
