### ISSUE TITLE
Добавить раскладку по-умолчанию

### ISSUE THREAD

**Issue by nnmalex** [Aegel5/SimpleSwitcher#64]
Сейчас по-умолчанию для новых окон программа выбирает русскую раскладку. Хорошо бы иметь возможность выбрать другую как основную.

**Comment by Aegel5** [comment]
Вообще, это настройка windows, какая раскладка имеет приоритет.  https://dzen.ru/a/X9NiDZSA7HjcM3WN
Но по идее новое окно должно с текущей раскладкой запускаться. У меня так работает.
