### ISSUE TITLE
Notify current layout

### ISSUE THREAD

**Issue by Aegel5** [Aegel5/SimpleSwitcher#9]
Нотификация текущего языка уже нужна много где:
- возможность реализовать флаги стран в трее
- Корректное ожидание layout changed
- Корректная работа фильтра и последовательности раскладок в консольных app

Но для реализации нужен инжект dll (32 и 64 бита)

**Comment by AnrDaemon** [comment]
А для нормальной работы инжекта нужна [корректная работа консольного  API](https://github.com/microsoft/terminal/issues/83).
Так же см. https://stackoverflow.com/questions/27720728/cant-send-wm-inputlangchangerequest-to-some-controls

**Comment by AnrDaemon** [comment]
Кстати, https://github.com/kurumpa/dotSwitcher
Возможно, там есть что подсмотреть.


P.S.
Пока поставил Curlyt (нашёл на просторах интернета). В семёрке работает без сбоев. Хотя отмена раскладки стала подтормаживать из-за индикатора, но несильно.

**Comment by Aegel5** [comment]
в mohau вроде есть код notify текущей раскладки через inject dll, но там такие хаки..

**Comment by Aegel5** [comment]
fixid for win 10 and later.
